name: noorbot_app
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  # sdk: ">=2.17.6 <3.0.0"
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^4.0.3

  percent_indicator: ^4.0.1

  ## -- STATE MANAGEMENT
  get: ^4.6.5

  ## -- OnBoarding PACKAGES
  liquid_swipe: ^3.0.0
  smooth_page_indicator: ^1.0.0+2

  ## -- OTP TEXT FIELD PACKAGE
  flutter_otp_text_field: ^1.1.1

  ## -- DAILOGFLOE PACKAGES
  dialogflow_flutter: ^1.0.0
  bubble:
  intl:

  google_sign_in: ^5.4.2

  ## -- ICON PACKAGES
  cupertino_icons: ^1.0.2
  line_awesome_flutter: ^2.0.0
  flutter_native_splash: ^2.2.16

  ## -- FIREBASE PACKAGES
  firebase_core: ^2.13.0
  firebase_auth: ^4.4.2
  cloud_firestore: ^4.2.0
  firebase_database: ^10.1.0
  firebase_storage: ^11.1.1
  shared_preferences: ^2.1.0
  cloud_functions: ^4.1.1
  # firebase_auth_web: ^5.3.2

  ## -- requests
  http: ^0.13.5
  flutter_markdown: ^0.6.14
  animations: ^2.0.7
  url_launcher: ^6.1.11
  firebase_messaging: ^14.6.1
  overlay_support: ^2.1.0

  ## -- GPT
  chat_gpt_sdk: 2.1.6

  fl_chart: ^0.62.0

  logger: ^1.3.0
  flutter_svg: ^2.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/logo/
    - assets/icons/
    - assets/images/
    - assets/fonts/
    - assets/images/profile/
    - assets/images/dashboard/
    - assets/images/splash_images/
    - assets/images/welcome_images/
    - assets/images/forget_password/
    - assets/images/on_boarding_images/

    - assets/service.json
    
  fonts:
    - family: Noto
      fonts:
        - asset: assets/fonts/NotoColorEmoji-Regular.ttf

# Splash screen has been added in the 'splash.yaml' file in main project directory
