// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQ3wjrp4KJFjz-CY_3WMyR333JSyynWfE',
    appId: '1:212443719146:android:8f85e3cf4200de4a4a3e93',
    messagingSenderId: '212443719146',
    projectId: 'noorbot-ai',
    databaseURL: 'https://noorbot-ai-default-rtdb.firebaseio.com',
    storageBucket: 'noorbot-ai.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJPldhWhuBzvxTBOilXOw2dXMEbczF5kQ',
    appId: '1:212443719146:ios:5d2073abae43af3e4a3e93',
    messagingSenderId: '212443719146',
    projectId: 'noorbot-ai',
    databaseURL: 'https://noorbot-ai-default-rtdb.firebaseio.com',
    storageBucket: 'noorbot-ai.appspot.com',
    iosClientId: '212443719146-ktsaq521b2h5m2dtmc6sht2ranjml4pp.apps.googleusercontent.com',
    iosBundleId: 'com.codingwitht.loginFlutterApp',
  );
}
